export const QUERY_KEYS = {
  CATEGORIES: "CATEGORIES",
  GALLERIES: "GALLERIES",
  GALLERY_DETAIL: "GALLERY_DETAIL",
  GALLERIES_HOMEPAGE: "GALLERIES_HOMEPAGE",
  GALLERIES_BY_TAG: "GALLERIES_BY_TAG",
  GALLERIES_RELATED: "GALLERIES_RELATED",
  FAVORITE_MODELS: "FAVORITE_MODELS",
};
